# Generated by Django 3.0.2 on 2020-01-09 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 8, 56, 29, 575784, tzinfo=utc), verbose_name='Date de naissance')),
                ('biographie', models.TextField(verbose_name='Biographie')),
                ('filmographie', models.TextField(verbose_name='Filmographie')),
                ('photo', models.FileField(upload_to='', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Acteur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('affiche', models.FileField(upload_to='', verbose_name='Affiche')),
                ('genre', models.CharField(max_length=200, verbose_name='Genre')),
                ('auteur', models.CharField(max_length=200, null=True, verbose_name='Auteur')),
                ('compositeur', models.CharField(max_length=200, null=True, verbose_name='Compositeur')),
                ('mise_en_scene', models.CharField(max_length=200, verbose_name='Mise en scène')),
                ('distibution', models.CharField(max_length=200, verbose_name='Distribution')),
                ('programmation', models.CharField(max_length=200, verbose_name='Programmation')),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('affiche', models.FileField(upload_to='', verbose_name='Affiche')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 8, 56, 29, 576786, tzinfo=utc), verbose_name='Date de sortie')),
                ('critiques', models.TextField(null=True, verbose_name='Critiques')),
                ('video', models.CharField(max_length=255, null=True, verbose_name='Vidéo')),
            ],
            options={
                'verbose_name': 'Film',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 8, 56, 29, 576786, tzinfo=utc), verbose_name='Date de naissance')),
                ('biographie', models.TextField(verbose_name='Biographie')),
                ('filmographie', models.TextField(verbose_name='Filmographie')),
                ('photo', models.FileField(upload_to='', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Réalisateur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255, null=True, verbose_name='Vidéo')),
                ('saison', models.IntegerField(verbose_name='Référence Saison')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre épisode')),
                ('episode', models.IntegerField(verbose_name='Référence épisode')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 8, 56, 29, 579787, tzinfo=utc), verbose_name='Date épisode')),
                ('affiche', models.FileField(upload_to='', verbose_name='Affiche épisode')),
                ('resume', models.TextField(verbose_name='Résumé épisode')),
                ('critiques', models.TextField(null=True, verbose_name='Critiques')),
            ],
            options={
                'verbose_name': 'Série',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, upload_to='profile_pics')),
                ('films', models.ManyToManyField(related_name='users', to='cineseries.Film')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineseries.Realisateur'),
        ),
        migrations.AddField(
            model_name='film',
            name='players',
            field=models.ManyToManyField(to='cineseries.Acteur'),
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom du cinéma')),
                ('adresse', models.CharField(max_length=50, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=30, verbose_name='Ville')),
                ('nb_places', models.IntegerField(verbose_name='Nombre de places')),
                ('films', models.ManyToManyField(related_name='cinemas', to='cineseries.Film')),
            ],
            options={
                'verbose_name': 'Cinéma',
                'ordering': ['nom'],
            },
        ),
    ]
